#########
# RESET #
#########
DROP DATABASE IF EXISTS CANAMITOBIKE;
CREATE DATABASE CANAMITOBIKE;
USE CANAMITOBIKE;
#############
# FIN RESET #
#############

################
# CREATE TABLE #
################
CREATE TABLE C_PROVINCE (
  C_PROVINCE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

  NAME VARCHAR(64) NOT NULL
)DEFAULT CHARSET=utf8mb4;

CREATE TABLE C_LOCALITY (
  C_LOCALITY_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

  POSTAL_CODE VARCHAR(5) NOT NULL,
  NAME VARCHAR(100) NOT NULL,

  C_PROVINCE_ID INT UNSIGNED UNSIGNED NOT NULL,
    FOREIGN KEY (C_PROVINCE_ID) REFERENCES C_PROVINCE(C_PROVINCE_ID)
)DEFAULT CHARSET=utf8mb4;

CREATE TABLE C_AUTHORIZER (
  C_AUTHORIZER_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  DNI VARCHAR(9) NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  SURNAME VARCHAR(128) NOT NULL
);

CREATE TABLE C_AUTHORIZER_DESCRIPTION (
  C_AUTHORIZER_DESCRIPTION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  DESCRIPTION VARCHAR (512) NOT NULL
);

CREATE TABLE C_PERSON (
  C_PERSON_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  DNI VARCHAR(9) NOT NULL UNIQUE,
  NAME VARCHAR(128) NOT NULL,
  SURNAME VARCHAR(128) NOT NULL,
  BORN_DATE DATE NOT NULL,
  ADDRESS VARCHAR(128) NOT NULL,
  PHONE_NUMBER VARCHAR(9) NOT NULL,

  C_LOCALITY_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_LOCALITY_ID) REFERENCES C_LOCALITY(C_LOCALITY_ID),
  C_AUTHORIZER_ID INT UNSIGNED,
    FOREIGN KEY (C_AUTHORIZER_ID) REFERENCES C_AUTHORIZER(C_AUTHORIZER_ID)
);

CREATE TABLE C_REGISTRATION (
  C_REGISTATION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  REGISTRATION_DATE DATE NOT NULL,

  C_AUTHORIZER_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_AUTHORIZER_ID) REFERENCES C_AUTHORIZER(C_AUTHORIZER_ID),
  C_AUTHORIZER_DESCRIPTION_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_AUTHORIZER_DESCRIPTION_ID) REFERENCES C_AUTHORIZER_DESCRIPTION(C_AUTHORIZER_DESCRIPTION_ID),
  C_PERSON_ID INT UNSIGNED NOT NULL UNIQUE,
    FOREIGN KEY (C_PERSON_ID) REFERENCES C_PERSON(C_PERSON_ID)
);

CREATE TABLE C_DIFFUSION (
  C_DIFFUSION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  
  DIFFUSION_DATE DATE NOT NULL,

  C_AUTHORIZER_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_AUTHORIZER_ID) REFERENCES C_AUTHORIZER(C_AUTHORIZER_ID),
  C_AUTHORIZER_DESCRIPTION_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_AUTHORIZER_DESCRIPTION_ID) REFERENCES C_AUTHORIZER_DESCRIPTION(C_AUTHORIZER_DESCRIPTION_ID),
  C_PERSON_ID INT UNSIGNED NOT NULL UNIQUE,
    FOREIGN KEY (C_PERSON_ID) REFERENCES C_PERSON(C_PERSON_ID)
);

CREATE TABLE C_ACCESS (
  C_ACCESS_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  NAME VARCHAR(64),
  DESCRIPTION VARCHAR(255),
  SERVLET_PATH VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE C_ROL (
  C_ROL_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  NAME VARCHAR(64) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(255)
);

CREATE TABLE C_ROL_ACCESS (
  C_ROL_ACCESS_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  C_ROL_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_ROL_ID) REFERENCES C_ROL(C_ROL_ID),
  C_ACCESS_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_ACCESS_ID) REFERENCES C_ACCESS(C_ACCESS_ID)
);

CREATE TABLE C_USER (
  C_USER_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  EMAIL VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD VARCHAR(64) NOT NULL,

  C_PERSON_ID INT UNSIGNED,
    FOREIGN KEY (C_PERSON_ID) REFERENCES C_PERSON(C_PERSON_ID),
  C_ROL_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_ROL_ID) REFERENCES C_ROL(C_ROL_ID)
);

CREATE TABLE C_RECOVERY (
  C_RECOVERY_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  RECOVERY_CODE MEDIUMINT UNSIGNED DEFAULT (FLOOR(100000 + (RAND() * 899999))) NOT NULL,
  TRIES_LEFT TINYINT UNSIGNED DEFAULT 3 NOT NULL,
  VALID_UNTIL DATETIME NOT NULL,

  C_USER_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_USER_ID) REFERENCES C_USER(C_USER_ID)
);

CREATE TABLE C_THEME (
  C_THEME_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  NAME VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(255),
  CSS_PATH VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE C_PREFERENCES (
  C_PREFERENCES_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  C_USER_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_USER_ID) REFERENCES C_USER(C_USER_ID),
  C_THEME_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_THEME_ID) REFERENCES C_THEME(C_THEME_ID)
);

CREATE TABLE C_GROUP (
  C_GROUP_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  GRADE TINYINT UNSIGNED NOT NULL,
  LETTER ENUM('A','B','C','D') NOT NULL
);

CREATE TABLE C_GROUP_PERSON (
  C_GROUP_PERSON INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  C_GROUP_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_GROUP_ID) REFERENCES C_GROUP(C_GROUP_ID),
  C_PERSON_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (C_PERSON_ID) REFERENCES C_PERSON(C_PERSON_ID)
);

####################
# FIN CREATE TABLE #
####################
