#########
# RESET #
#########
USE CANAMITOBIKE;

SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM C_PROVINCE;
DELETE FROM C_LOCALITY;
DELETE FROM C_AUTHORIZER;
DELETE FROM C_AUTHORIZER_DESCRIPTION;
DELETE FROM C_REGISTRATION;
DELETE FROM C_DIFFUSION;
DELETE FROM C_PERSON;
DELETE FROM C_ACCESS;
DELETE FROM C_ROL;
DELETE FROM C_ROL_ACCESS;
DELETE FROM C_USER;
DELETE FROM C_RECOVERY;
DELETE FROM C_THEME;
DELETE FROM C_PREFERENCES;
DELETE FROM C_GROUP;
DELETE FROM C_GROUP_PERSON;
SET FOREIGN_KEY_CHECKS = 1;
#############
# FIN RESET #
#############

##########
# INSERT #
##########
INSERT INTO C_PROVINCE (C_PROVINCE_ID, NAME) VALUES('39', 'Cantabria');
INSERT INTO C_PROVINCE (C_PROVINCE_ID, NAME) VALUES('40', 'Segovia');
INSERT INTO C_PROVINCE (C_PROVINCE_ID, NAME) VALUES('41', 'Sevilla');
INSERT INTO C_PROVINCE (C_PROVINCE_ID, NAME) VALUES('42', 'Soria');
INSERT INTO C_PROVINCE (C_PROVINCE_ID, NAME) VALUES('43', 'Tarragona');

INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34062, '41898', 'Alamo, El (el Madroño)', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34063, '41380', 'Alanis', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34086, '41930', 'Bormujos', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34087, '41310', 'Brenes', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34090, '41610', 'Calvario, El', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34091, '41900', 'Camas', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34119, '41760', 'Coronil, El', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34224, '41440', 'Rincon, El', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34225, '41309', 'La Rinconada', '41');
INSERT INTO C_LOCALITY (C_LOCALITY_ID, POSTAL_CODE, NAME, C_PROVINCE_ID) VALUES(34258, '41100', 'Vega, La', '41');

INSERT INTO C_AUTHORIZER (DNI, NAME, SURNAME) VALUES ('11111111Z', 'au_Pedro', 'au_García');
INSERT INTO C_AUTHORIZER (DNI, NAME, SURNAME) VALUES ('22222222X', 'au_Pedro', 'au_García');
INSERT INTO C_AUTHORIZER (DNI, NAME, SURNAME) VALUES ('33333333C', 'au_Pedro', 'au_García');
INSERT INTO C_AUTHORIZER (DNI, NAME, SURNAME) VALUES ('44444444V', 'au_Pedro', 'au_García');

INSERT INTO C_AUTHORIZER_DESCRIPTION (DESCRIPTION) VALUES ('Autorizo a que mi hijo pueda realizar las actividades del curso');

INSERT INTO C_PERSON (DNI, NAME, SURNAME, BORN_DATE, ADDRESS, PHONE_NUMBER, C_LOCALITY_ID, C_AUTHORIZER_ID) 
	VALUES ('');

INSERT INTO C_REGISTRATION (REGISTRATION_DATE, C_AUTHORIZER_ID, C_AUTHORIZER_DESCRIPTION_ID, C_PERSON_ID) VALUES ('2012-06-21', 1, 1);

INSERT INTO C_ACCESS () VALUES ();

INSERT INTO C_ACCESS () VALUES ();

INSERT INTO C_ACCESS () VALUES ();

INSERT INTO C_ACCESS () VALUES ();

INSERT INTO C_ACCESS () VALUES ();
##############
# FIN INSERT #
##############